version: 2.1
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  build:
    docker:
      - image: "cimg/node:14.15"

    steps:
      - node/install:
          node-version: "16.14.2"
      - checkout
      - run:
          name: Install Front-End Dependencies
          command: npm run udagram-frontend:install
      - run:
          name: Install API Dependencies
          command: npm run udagram-api:install
      - run:
          name: Front-End Build
          command: npm run udagram-frontend:build
      - run:
          name: API Build
          command: npm run udagram-api:build

  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: "16.14.2"
      - eb/setup
      - aws-cli/setup
      - checkout
      - run:
          name: Deploy frontend
          command: npm run udagram-frontend:deploy
      - run:
          name: Deplot api
          command: npm run udagram-api:deploy
workflows:
  Build_Deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - deploy:
          filters:
            branches:
              only: main

branch-defaults:
  main:
    environment: udagram-server-api-dev
global:
  application_name: udagram-api
  default_ec2_keyname: udagram-server-api-dev
  default_platform: 64bit Amazon Linux 2017.09 v2.6.2 running Ruby 2.4 (Passenger Standalone)
  default_region: us-east-1
  sc: git
