version: 2.1
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  build:
    docker:
      - image: "cimg/node:14.15"

    steps:
      - node/install:
          node-version: "16.14.2"
      - checkout
      - run:
          name: Install Front-End Dependencies
          command: npm run frontend:install
      - run:
          name: Install API Dependencies
          command: npm run api:install
      - run:
          name: Front-End Build
          command: npm run frontend:build
      - run:
          name: API Build
          command: npm run api:build

  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: "16.14.2"
      - eb/setup
      - aws-cli/setup
      - checkout
      - run:
          name: Deploy frontend
          command: npm run frontend:deploy
      - run:
          name: Deplot api
          command: npm run api:deploy
workflows:
  Build_Deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - deploy:
          filters:
            branches:
              only: main
